### ISSUE TITLE
Adding Badges

### ISSUE THREAD

**Issue by rodneyosodo** [WilliamOtieno/python-flutterwave#1]
Add badges for
- [x] Test passing
- [ ] Coverage report
- [ ] Maintenance report

**Comment by Qodestackr** [comment]
Haha ..Thought it's an Ethereum address 💯🔥. Wants also to be part of this OSS💯

**Comment by WilliamOtieno** [comment]
> Haha ..Thought it's an Ethereum address 100fire. Wants also to be part of this OSS100

No problem, there is a contribution guide in the project

**Comment by WilliamOtieno** [comment]
> Add badges for
> 
> * [x]  Test passing
> * [ ]  Coverage report
> * [ ]  Maintenance report

You can help out with this
