### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by rodneyosodo** [WilliamOtieno/python-flutterwave#5]
Could you list some of the API endpoints that you have not done as separate issues individually

**Comment by WilliamOtieno** [comment]
- Account payments through `https://api.flutterwave.com/v3/charges?type=debit_ng_account`
 - UK Account payments through `https://api.flutterwave.com/v3/charges?type=debit_uk_account`
 - Rwanda Mobile Money through `https://api.flutterwave.com/v3/charges?type=mobile_money_rwanda`
 - Uganda Mobile Money through `https://api.flutterwave.com/v3/charges?type=mobile_money_uganda`
 - Zambia Mobile Money through `https://api.flutterwave.com/v3/charges?type=mobile_money_zambia`
 - Ghana mobile money through `https://api.flutterwave.com/v3/charges?type=mobile_money_ghana`

##### Kindly refer to `https://developer.flutterwave.com/docs` under the `PAYMENT METHODS` section.
